[features]
seeds = false
skip-lint = false
[programs.localnet]
signed_ix = "3Y8xtAeH3JC1B8xKbQk2m632fjJF21XBKySxGLyduun1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/arowana/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
